### ISSUE TITLE
Typo "Where a is the sample mean ( 𝑥¯ ) and popmean ( 𝜇 ) is the population mean."

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-t-tests#3]
Per documentation, **a** is an array (or our sample data), not the sample mean. Please review this. once possible 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_1samp.html

**Comment by hoffm386** [comment]
Thanks for flagging! This is explained more clearly in the latest version, which explains that "a" is an "array-like" variable representing the sample
